"""add_admin_features_and_credits

Revision ID: a120f6de02f4
Revises: db595064c79e
Create Date: 2025-12-11 06:27:49.219383

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a120f6de02f4'
down_revision = 'db595064c79e'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('credit_transactions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('amount', sa.Integer(), nullable=False),
    sa.Column('transaction_type', sa.String(), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('report_id', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['report_id'], ['reports.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_credit_transactions_id'), 'credit_transactions', ['id'], unique=False)
    
    # Add status column as nullable first, then set defaults, then make NOT NULL
    op.add_column('reports', sa.Column('status', sa.String(), nullable=True))
    op.execute("UPDATE reports SET status = 'completed' WHERE status IS NULL")
    op.alter_column('reports', 'status', nullable=False, server_default='completed')
    
    # Add user columns
    op.add_column('users', sa.Column('phone', sa.String(), nullable=True))
    op.add_column('users', sa.Column('company', sa.String(), nullable=True))
    op.add_column('users', sa.Column('is_admin', sa.Integer(), nullable=True, server_default='0'))
    op.add_column('users', sa.Column('status', sa.String(), nullable=True))
    op.execute("UPDATE users SET status = 'active' WHERE status IS NULL")
    op.alter_column('users', 'is_admin', nullable=False)
    op.alter_column('users', 'status', nullable=False, server_default='active')
    op.add_column('users', sa.Column('last_login', sa.DateTime(timezone=True), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'last_login')
    op.drop_column('users', 'status')
    op.drop_column('users', 'is_admin')
    op.drop_column('users', 'company')
    op.drop_column('users', 'phone')
    op.drop_column('reports', 'status')
    op.drop_index(op.f('ix_credit_transactions_id'), table_name='credit_transactions')
    op.drop_table('credit_transactions')
    # ### end Alembic commands ###

