"""Add s3_key to reports

Revision ID: db595064c79e
Revises: c3b2a25da9bb
Create Date: 2025-12-05 09:40:38.682045

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'db595064c79e'
down_revision = 'c3b2a25da9bb'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('reports', sa.Column('s3_key', sa.String(), nullable=True))
    op.alter_column('reports', 'user_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('reports', 'user_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.drop_column('reports', 's3_key')
    # ### end Alembic commands ###

